import type { Models } from "node-appwrite";

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ./types`.

export enum ElderlyStatus {
  NORMAL = "Normal",
  WARNING = "Warning",
  DANGER = "Danger",
}

export enum ElderlyMedicationStatus {
  PENDING = "Pending",
  COMPLETED = "Completed",
  EXPIRED = "Expired",
}

export enum ScheduleStatus {
  PENDING = "Pending",
  COMPLETED = "Completed",
  MISSED = "Missed",
}

export enum ScheduleType {
  MEDICATION = "medication",
  APPOINTMENT = "appointment",
  MEAL = "meal",
  ACTIVITY = "activity",
  CHECKUP = "checkup",
}

export enum ScheduleMedicationStatus {
  MISSED = "Missed",
  PENDING = "Pending",
  COMPLETED = "Completed",
}

export type Elderly = Models.Row & {
  user_id: string;
  name: string;
  phone: string | null;
  birth: string | null;
  status: ElderlyStatus | null;
  gender: string | null;
  blood_type: string | null;
  emergency_contact: string | null;
};

export type Caregiver = Models.Row & {
  user_id: string;
  name: string | null;
  phone: string | null;
  birth: string | null;
};

export type CaregiverElderly = Models.Row & {
  caregiver: Caregiver;
  elderly: Elderly;
};

export type Medication = Models.Row & {
  name: string | null;
  unit: string | null;
};

export type ElderlyMedication = Models.Row & {
  dosage: number | null;
  frequency: string | null;
  is_prn: boolean;
  times_per_day: number | null;
  status: ElderlyMedicationStatus | null;
  last_taken: string | null;
  notes: string | null;
  approx_times: string[] | null;
  elderly: Elderly;
  medication: Medication;
};

export type Schedule = Models.Row & {
  time: string | null;
  title: string | null;
  description: string | null;
  status: ScheduleStatus | null;
  type: ScheduleType | null;
  elderly: Elderly;
  scheduleCategory: ScheduleCategory;
};

export type ScheduleCategory = Models.Row & {
  name: string | null;
  color_hex: string | null;
  svg_icon: string | null;
};

export type ScheduleMedication = Models.Row & {
  schedule: Schedule;
  elderlyMedication: ElderlyMedication;
  status: ScheduleMedicationStatus | null;
};

export type HealthData = Models.Row & {
  elderly: Elderly[];
  time: string | null;
  type: string | null;
  data: string | null;
  value: string | null;
  unit: string | null;
};

export type ElderlyMedicationReminder = Models.Row & {
  start_date: string;
  duration_days: number;
  follow_up_caregiver: string | null;
  after_meal: boolean;
  reminder_times: string[];
  elderly: Elderly;
  elderly_medication: ElderlyMedication;
  active: boolean;
  is_finished: boolean;
  end_date: string | null;
};

export type MedicationLogs = Models.Row & {
  scheduled_at: string;
  taken_at: string | null;
  status: string;
  elderly_medication_reminder: ElderlyMedicationReminder;
  elderly: Elderly;
};

export type ChatSession = Models.Row & {
  user_id: string;
  title: string;
  messages: string;
};

export type ElderlyDailySteps = Models.Row & {
  elderlyId: string;
  date: string;
  steps: number;
  lastUpdated: string;
  source: string;
};
