import type { Models } from 'node-appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types ./types`.

export enum ElderlyStatus {
    NORMAL = "Normal",
    WARNING = "Warning",
    DANGER = "Danger"
}

export enum ElderlyMedicationStatus {
    PENDING = "Pending",
    COMPLETED = "Completed",
    EXPIRED = "Expired"
}

export enum ScheduleStatus {
    PENDING = "Pending",
    COMPLETED = "Completed",
    MISSED = "Missed"
}

export type ElderlyT1Test = Models.Row & {
    name: string;
    phone: string | null;
    age: number;
    status: string | null;
    originalId: number;
    aaa: string[] | null;
}

export type Elderly = Models.Row & {
    user_id: string;
    name: string;
    phone: string | null;
    birth: string | null;
    status: ElderlyStatus | null;
}

export type Caregiver = Models.Row & {
    user_id: string;
    name: string | null;
    phone: string | null;
    birth: string | null;
}

export type CaregiverElderly = Models.Row & {
    caregiver: Caregiver[];
    elderly: Elderly[];
}

export type Medication = Models.Row & {
    name: string | null;
    unit: string | null;
}

export type ElderlyMedication = Models.Row & {
    elderly: Elderly[];
    medication: Medication[];
    dosage: number | null;
    frequency: string | null;
    is_prn: boolean;
    times_per_day: number | null;
    approx_times: string[] | null;
    status: ElderlyMedicationStatus | null;
    last_taken: string | null;
    notes: string | null;
}

export type Schedule = Models.Row & {
    time: string | null;
    title: string | null;
    description: string | null;
    elderly: Elderly[];
    scheduleCategory: ScheduleCategory[];
    status: ScheduleStatus | null;
}

export type ScheduleCategory = Models.Row & {
    name: string | null;
    color_hex: string | null;
    svg_icon: string | null;
}

export type ScheduleMedication = Models.Row & {
    schedule: Schedule[];
    elderly_medication: ElderlyMedication[];
}

export type HealthData = Models.Row & {
    elderly: Elderly[];
    time: string | null;
    type: string | null;
}
